apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: foto
  name: bilde-api
  namespace: foto
spec:
  image: 'europe-north1-docker.pkg.dev/nais-337909/nais-poc/foto-ui-backend:0.1.0'
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: utv
    - name: BILDE_API_URL
      value: http://bilde-api.foto
    - name: USER_METRICS_USER_SALT
      value: "1111111111111111111111"
  liveness:
    initialDelay: 10
    path: /actuator/health
    port: 8081
    timeout: 60
  readiness:
    initialDelay: 10
    path: /actuator/health
    port: 8081
    timeout: 60
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: '1'
      memory: 600Mi
    requests:
      cpu: 100m
      memory: 600Mi
  skipCaBundle: true
