apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: foto
  name: bilde-api
  namespace: foto
spec:
  image: 'europe-north1-docker.pkg.dev/nais-337909/nais-poc/bilde-api:0.12.0'
  accessPolicy:
    inbound:
      rules:
        - application: foto-ui-backend
  gcp:
    buckets:
    - name: foto-bilde-api
    sqlInstances:
      - name: bilde-api
        type: POSTGRES_12
        databases:
          - name: bilde-api-db
            envVarPrefix: DATABASE          
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: utv
    - name: IMAGE_HOMEDIR
      value: /tmp
  envFrom:
    - secret: google-sql-bilde-api
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: '2'
      memory: 1200Mi
    requests:
      cpu: 150m
      memory: 1000Mi
  skipCaBundle: true
